/**
 * Auto-generated indicator registry — 292 indicators from lightweight-charts-indicators.
 */
import {
  SMA,
  ADR,
  ALMA,
  ATR,
  BollingerBands,
  BOP,
  CCI,
  DEMA,
  DonchianChannels,
  EMA,
  HMA,
  IchimokuCloud,
  KeltnerChannels,
  LSMA,
  MACD,
  MARibbon,
  MassIndex,
  McGinleyDynamic,
  Momentum,
  OBV,
  ParabolicSAR,
  RMA,
  ROC,
  RSI,
  Stochastic,
  Supertrend,
  ADX,
  AwesomeOscillator,
  BBTrend,
  BullBearPower,
  ChandeMO,
  DPO,
  ElderForceIndex,
  HistoricalVolatility,
  MACross,
  Median,
  MFI,
  PVT,
  RVI,
  SMIErgodic,
  SMIErgodicOscillator,
  SMMA,
  StandardDeviation,
  StochRSI,
  TrendStrengthIndex,
  TSI,
  VolumeOscillator,
  VortexIndicator,
  WilliamsAlligator,
  WilliamsPercentRange,
  WoodiesCCI,
  BBPercentB,
  BBBandWidth,
  ChaikinMF,
  Envelope,
  PriceOscillator,
  Aroon,
  CoppockCurve,
  Choppiness,
  EaseOfMovement,
  ChaikinOscillator,
  TEMA,
  ZigZag,
  FisherTransform,
  TRIX,
  DMI,
  KlingerOscillator,
  UltimateOscillator,
  ChandeKrollStop,
  RelativeVolumeAtTime,
  RCIRibbon,
  VolumeDelta,
  CumulativeVolumeDelta,
  NetVolume,
  VWMA,
  WMA,
  KnowSureThing,
  ConnorsRSI,
  ChopZone,
  RankCorrelationIndex,
  RelativeVolatilityIndex,
  WilliamsFractals,
  TWAP,
  BollingerBars,
  MoonPhases,
  ZLSMA,
  ForecastOscillator,
  CCTBBO,
  MACD4C,
  ColoredVolume,
  KDJ,
  WaveTrend,
  SqueezeMomentum,
  CoralTrend,
  ChandelierExit,
  ImpulseMACD,
  SchaffTrendCycle,
  DonchianTrendRibbon,
  OBVMACD,
  AlphaTrend,
  HalfTrend,
  QQEMod,
  FollowLine,
  UTBot,
  HullSuite,
  OptimizedTrendTracker,
  TrendMagic,
  SSLChannel,
  MavilimW,
  CDCActionZone,
  TillsonT3,
  WaddahAttarExplosion,
  RipsterEMAClouds,
  PremierRSI,
  LaguerreRSI,
  RSICandles,
  ZeroLagMACD,
  AwesomeOscillatorV2,
  CMEMATrendBars,
  BBFibonacciRatios,
  AverageSentimentOscillator,
  ATRTrailingStops,
  AccurateSwingTrading,
  BullBearPowerTrend,
  BBBreakoutOscillator,
  ChandelierStop,
  StochasticMomentumIndex,
  VolumeFlowIndicator,
  EhlersInstantaneousTrend,
  PriceMomentumOscillator,
  FibonacciBollingerBands,
  TrendTriggerFactor,
  ElliottWaveOscillator,
  MadridTrendSqueeze,
  KaufmanAdaptiveMA,
  WilliamsVixFix,
  EhlersMESAMA,
  GannHighLow,
  CMSlingShot,
  RangeIdentifier,
  SmoothedHeikenAshi,
  MACDLeader,
  IFTStochRSICCI,
  VariableMA,
  OBVOscillator,
  GMMA,
  TurtleTradeChannels,
  LinearRegressionChannel,
  TwinRangeFilter,
  TMABands,
  EhlersStochasticCG,
  VPCI,
  PremierStochastic,
  VolumeAccumulationPct,
  VervoortHAOscillator,
  ADXCobra,
  AIEngulfing,
  AKTrendID,
  AllCandlestickPatterns,
  AntiVolumeStop,
  ATRPlus,
  ATRTrailingColored,
  AutoFib,
  AutoSupport,
  AutoSupportResistance,
  BBStochRSI,
  BinaryOptionArrows,
  BitcoinKillZones,
  BullishEngulfingFinder,
  BullsBears,
  BuyingSellVolume,
  BuySellPressure,
  CandlestickReversal,
  CCIOBV,
  CMEnhancedIchimoku,
  CMGannSwing,
  CMGuppyEMA,
  CMHeikinAshi,
  CMLaguerrePPO,
  CMPriceAction,
  CMRSI2Lower,
  CMRSI2Upper,
  CMRSIPlusEMA,
  CMStochHighlight,
  CMTimeLines,
  CMVixFixV3,
  COGChannel,
  DarvasBox,
  DMIADX,
  DonchianCustom,
  EasyTrendColors,
  EMAEnveloper,
  EMAMACross,
  EMAMulti,
  EMARibbon,
  EMASupertrend,
  EMAWave,
  EntryPoints,
  EnvelopeRSI,
  EVWMAEnvelope,
  FaithIndicator,
  FibonacciLevels,
  FibonacciZone,
  ForexSessions,
  FXSniperT3CCI,
  HawkEyeVolume,
  IchimokuEMABands,
  IntradayBuySell,
  IntradayTSBB,
  IsolatedPeakBottom,
  LeledcLevels,
  LinRegCandles,
  MAADX,
  MACDAS,
  MACDBB,
  MACDCrossover,
  MACDDEMA,
  MACDDivergence,
  MACDVXI,
  MAColored,
  MADeviationRate,
  MarketCipherA,
  MarketCipherB,
  MarketShiftLevels,
  MAShadedFill,
  MAShift,
  MatrixSeries,
  MFIRSIBollingerBands,
  ModifiedHeikinAshi,
  MultipleMA,
  MurreysOscillator,
  NormalizedQQE,
  ParallelPivotLines,
  PhilakoneEMASwing,
  PivotPointSupertrend,
  PPOAlerts,
  PPODivergence,
  PriceActionSystem,
  QQE,
  QQESignals,
  RCI3Lines,
  RedKRSSWMA,
  ReversalCandleSetup,
  RSIBands,
  RSIBBDispersion,
  RSIDivergence,
  RSIHistoAlert,
  RSISnabbel,
  RSISwingSignal,
  RSSupportResistance,
  SAREMAMACDSignals,
  ScalpingLine,
  SellBuyRates,
  SignalMA,
  SimpleMovingAverages,
  SlowHeikenAshi,
  SMIUCS,
  SqueezeMomentumV2,
  SRLevelsBreaks,
  ST0P,
  StochasticOTT,
  StochPOP1,
  StochPOP2,
  StochVX3,
  SuperSmoothedMACD,
  SuperSupertrend,
  SupertrendChannels,
  SwingTradeSignals,
  TDIHLCTrix,
  TDMacd,
  ThreeMovingAverages,
  TonyUXScalper,
  TopBottomCandle,
  TopsBottoms,
  TRAMA,
  TransientZones,
  TrendFollowingMA,
  TrendTrader,
  TriangularMomentumOsc,
  TripleMAForecast,
  TTMSqueezePro,
  VdubSniper,
  VdubusBinaryPro,
  VolumeColoredBars,
  VolumeFlowV3,
  VolumeLinRegTrend,
  VWMACDSZO,
  VWMACDV2,
  WeisWaveVolume,
  WickedFractals,
  WilliamsCombo,
  ZeroLagEMA
} from 'lightweight-charts-indicators';

export interface IndicatorModule {
  metadata: { title: string; shortTitle: string; overlay: boolean };
  calculate: (bars: any[], inputs?: any) => any;
  plotConfig: any[];
  defaultInputs: Record<string, any>;
  inputConfig?: any[];
  hlineConfig?: any[];
}

interface RegistryEntry {
  module: IndicatorModule;
}

const raw: RegistryEntry[] = [
  { module: SMA as any },
  { module: ADR as any },
  { module: ALMA as any },
  { module: ATR as any },
  { module: BollingerBands as any },
  { module: BOP as any },
  { module: CCI as any },
  { module: DEMA as any },
  { module: DonchianChannels as any },
  { module: EMA as any },
  { module: HMA as any },
  { module: IchimokuCloud as any },
  { module: KeltnerChannels as any },
  { module: LSMA as any },
  { module: MACD as any },
  { module: MARibbon as any },
  { module: MassIndex as any },
  { module: McGinleyDynamic as any },
  { module: Momentum as any },
  { module: OBV as any },
  { module: ParabolicSAR as any },
  { module: RMA as any },
  { module: ROC as any },
  { module: RSI as any },
  { module: Stochastic as any },
  { module: Supertrend as any },
  { module: ADX as any },
  { module: AwesomeOscillator as any },
  { module: BBTrend as any },
  { module: BullBearPower as any },
  { module: ChandeMO as any },
  { module: DPO as any },
  { module: ElderForceIndex as any },
  { module: HistoricalVolatility as any },
  { module: MACross as any },
  { module: Median as any },
  { module: MFI as any },
  { module: PVT as any },
  { module: RVI as any },
  { module: SMIErgodic as any },
  { module: SMIErgodicOscillator as any },
  { module: SMMA as any },
  { module: StandardDeviation as any },
  { module: StochRSI as any },
  { module: TrendStrengthIndex as any },
  { module: TSI as any },
  { module: VolumeOscillator as any },
  { module: VortexIndicator as any },
  { module: WilliamsAlligator as any },
  { module: WilliamsPercentRange as any },
  { module: WoodiesCCI as any },
  { module: BBPercentB as any },
  { module: BBBandWidth as any },
  { module: ChaikinMF as any },
  { module: Envelope as any },
  { module: PriceOscillator as any },
  { module: Aroon as any },
  { module: CoppockCurve as any },
  { module: Choppiness as any },
  { module: EaseOfMovement as any },
  { module: ChaikinOscillator as any },
  { module: TEMA as any },
  { module: ZigZag as any },
  { module: FisherTransform as any },
  { module: TRIX as any },
  { module: DMI as any },
  { module: KlingerOscillator as any },
  { module: UltimateOscillator as any },
  { module: ChandeKrollStop as any },
  { module: RelativeVolumeAtTime as any },
  { module: RCIRibbon as any },
  { module: VolumeDelta as any },
  { module: CumulativeVolumeDelta as any },
  { module: NetVolume as any },
  { module: VWMA as any },
  { module: WMA as any },
  { module: KnowSureThing as any },
  { module: ConnorsRSI as any },
  { module: ChopZone as any },
  { module: RankCorrelationIndex as any },
  { module: RelativeVolatilityIndex as any },
  { module: WilliamsFractals as any },
  { module: TWAP as any },
  { module: BollingerBars as any },
  { module: MoonPhases as any },
  { module: ZLSMA as any },
  { module: ForecastOscillator as any },
  { module: CCTBBO as any },
  { module: MACD4C as any },
  { module: ColoredVolume as any },
  { module: KDJ as any },
  { module: WaveTrend as any },
  { module: SqueezeMomentum as any },
  { module: CoralTrend as any },
  { module: ChandelierExit as any },
  { module: ImpulseMACD as any },
  { module: SchaffTrendCycle as any },
  { module: DonchianTrendRibbon as any },
  { module: OBVMACD as any },
  { module: AlphaTrend as any },
  { module: HalfTrend as any },
  { module: QQEMod as any },
  { module: FollowLine as any },
  { module: UTBot as any },
  { module: HullSuite as any },
  { module: OptimizedTrendTracker as any },
  { module: TrendMagic as any },
  { module: SSLChannel as any },
  { module: MavilimW as any },
  { module: CDCActionZone as any },
  { module: TillsonT3 as any },
  { module: WaddahAttarExplosion as any },
  { module: RipsterEMAClouds as any },
  { module: PremierRSI as any },
  { module: LaguerreRSI as any },
  { module: RSICandles as any },
  { module: ZeroLagMACD as any },
  { module: AwesomeOscillatorV2 as any },
  { module: CMEMATrendBars as any },
  { module: BBFibonacciRatios as any },
  { module: AverageSentimentOscillator as any },
  { module: ATRTrailingStops as any },
  { module: AccurateSwingTrading as any },
  { module: BullBearPowerTrend as any },
  { module: BBBreakoutOscillator as any },
  { module: ChandelierStop as any },
  { module: StochasticMomentumIndex as any },
  { module: VolumeFlowIndicator as any },
  { module: EhlersInstantaneousTrend as any },
  { module: PriceMomentumOscillator as any },
  { module: FibonacciBollingerBands as any },
  { module: TrendTriggerFactor as any },
  { module: ElliottWaveOscillator as any },
  { module: MadridTrendSqueeze as any },
  { module: KaufmanAdaptiveMA as any },
  { module: WilliamsVixFix as any },
  { module: EhlersMESAMA as any },
  { module: GannHighLow as any },
  { module: CMSlingShot as any },
  { module: RangeIdentifier as any },
  { module: SmoothedHeikenAshi as any },
  { module: MACDLeader as any },
  { module: IFTStochRSICCI as any },
  { module: VariableMA as any },
  { module: OBVOscillator as any },
  { module: GMMA as any },
  { module: TurtleTradeChannels as any },
  { module: LinearRegressionChannel as any },
  { module: TwinRangeFilter as any },
  { module: TMABands as any },
  { module: EhlersStochasticCG as any },
  { module: VPCI as any },
  { module: PremierStochastic as any },
  { module: VolumeAccumulationPct as any },
  { module: VervoortHAOscillator as any },
  { module: ADXCobra as any },
  { module: AIEngulfing as any },
  { module: AKTrendID as any },
  { module: AllCandlestickPatterns as any },
  { module: AntiVolumeStop as any },
  { module: ATRPlus as any },
  { module: ATRTrailingColored as any },
  { module: AutoFib as any },
  { module: AutoSupport as any },
  { module: AutoSupportResistance as any },
  { module: BBStochRSI as any },
  { module: BinaryOptionArrows as any },
  { module: BitcoinKillZones as any },
  { module: BullishEngulfingFinder as any },
  { module: BullsBears as any },
  { module: BuyingSellVolume as any },
  { module: BuySellPressure as any },
  { module: CandlestickReversal as any },
  { module: CCIOBV as any },
  { module: CMEnhancedIchimoku as any },
  { module: CMGannSwing as any },
  { module: CMGuppyEMA as any },
  { module: CMHeikinAshi as any },
  { module: CMLaguerrePPO as any },
  { module: CMPriceAction as any },
  { module: CMRSI2Lower as any },
  { module: CMRSI2Upper as any },
  { module: CMRSIPlusEMA as any },
  { module: CMStochHighlight as any },
  { module: CMTimeLines as any },
  { module: CMVixFixV3 as any },
  { module: COGChannel as any },
  { module: DarvasBox as any },
  { module: DMIADX as any },
  { module: DonchianCustom as any },
  { module: EasyTrendColors as any },
  { module: EMAEnveloper as any },
  { module: EMAMACross as any },
  { module: EMAMulti as any },
  { module: EMARibbon as any },
  { module: EMASupertrend as any },
  { module: EMAWave as any },
  { module: EntryPoints as any },
  { module: EnvelopeRSI as any },
  { module: EVWMAEnvelope as any },
  { module: FaithIndicator as any },
  { module: FibonacciLevels as any },
  { module: FibonacciZone as any },
  { module: ForexSessions as any },
  { module: FXSniperT3CCI as any },
  { module: HawkEyeVolume as any },
  { module: IchimokuEMABands as any },
  { module: IntradayBuySell as any },
  { module: IntradayTSBB as any },
  { module: IsolatedPeakBottom as any },
  { module: LeledcLevels as any },
  { module: LinRegCandles as any },
  { module: MAADX as any },
  { module: MACDAS as any },
  { module: MACDBB as any },
  { module: MACDCrossover as any },
  { module: MACDDEMA as any },
  { module: MACDDivergence as any },
  { module: MACDVXI as any },
  { module: MAColored as any },
  { module: MADeviationRate as any },
  { module: MarketCipherA as any },
  { module: MarketCipherB as any },
  { module: MarketShiftLevels as any },
  { module: MAShadedFill as any },
  { module: MAShift as any },
  { module: MatrixSeries as any },
  { module: MFIRSIBollingerBands as any },
  { module: ModifiedHeikinAshi as any },
  { module: MultipleMA as any },
  { module: MurreysOscillator as any },
  { module: NormalizedQQE as any },
  { module: ParallelPivotLines as any },
  { module: PhilakoneEMASwing as any },
  { module: PivotPointSupertrend as any },
  { module: PPOAlerts as any },
  { module: PPODivergence as any },
  { module: PriceActionSystem as any },
  { module: QQE as any },
  { module: QQESignals as any },
  { module: RCI3Lines as any },
  { module: RedKRSSWMA as any },
  { module: ReversalCandleSetup as any },
  { module: RSIBands as any },
  { module: RSIBBDispersion as any },
  { module: RSIDivergence as any },
  { module: RSIHistoAlert as any },
  { module: RSISnabbel as any },
  { module: RSISwingSignal as any },
  { module: RSSupportResistance as any },
  { module: SAREMAMACDSignals as any },
  { module: ScalpingLine as any },
  { module: SellBuyRates as any },
  { module: SignalMA as any },
  { module: SimpleMovingAverages as any },
  { module: SlowHeikenAshi as any },
  { module: SMIUCS as any },
  { module: SqueezeMomentumV2 as any },
  { module: SRLevelsBreaks as any },
  { module: ST0P as any },
  { module: StochasticOTT as any },
  { module: StochPOP1 as any },
  { module: StochPOP2 as any },
  { module: StochVX3 as any },
  { module: SuperSmoothedMACD as any },
  { module: SuperSupertrend as any },
  { module: SupertrendChannels as any },
  { module: SwingTradeSignals as any },
  { module: TDIHLCTrix as any },
  { module: TDMacd as any },
  { module: ThreeMovingAverages as any },
  { module: TonyUXScalper as any },
  { module: TopBottomCandle as any },
  { module: TopsBottoms as any },
  { module: TRAMA as any },
  { module: TransientZones as any },
  { module: TrendFollowingMA as any },
  { module: TrendTrader as any },
  { module: TriangularMomentumOsc as any },
  { module: TripleMAForecast as any },
  { module: TTMSqueezePro as any },
  { module: VdubSniper as any },
  { module: VdubusBinaryPro as any },
  { module: VolumeColoredBars as any },
  { module: VolumeFlowV3 as any },
  { module: VolumeLinRegTrend as any },
  { module: VWMACDSZO as any },
  { module: VWMACDV2 as any },
  { module: WeisWaveVolume as any },
  { module: WickedFractals as any },
  { module: WilliamsCombo as any },
  { module: ZeroLagEMA as any }
];

export interface IndicatorInfo {
  id: string;
  title: string;
  shortTitle: string;
  overlay: boolean;
  module: IndicatorModule;
}

function buildRegistry(): IndicatorInfo[] {
  const seen = new Set<string>();
  const result: IndicatorInfo[] = [];

  for (const e of raw) {
    if (!e.module?.metadata?.title) continue;
    let id = (e.module.metadata.shortTitle || e.module.metadata.title)
      .toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    if (seen.has(id)) {
      let n = 2;
      while (seen.has(id + '-' + n)) n++;
      id = id + '-' + n;
    }
    seen.add(id);
    result.push({
      id,
      title: e.module.metadata.title,
      shortTitle: e.module.metadata.shortTitle || e.module.metadata.title,
      overlay: e.module.metadata.overlay,
      module: e.module,
    });
  }
  return result;
}

export const indicators = buildRegistry();
export const overlayIndicators = indicators.filter(i => i.overlay);
export const oscillatorIndicators = indicators.filter(i => !i.overlay);

export function findIndicator(id: string): IndicatorInfo | undefined {
  return indicators.find(i => i.id === id);
}

export function searchIndicators(query: string): IndicatorInfo[] {
  const q = query.toLowerCase().trim();
  if (!q) return indicators;
  return indicators.filter(i =>
    i.title.toLowerCase().includes(q) ||
    i.shortTitle.toLowerCase().includes(q) ||
    i.id.includes(q)
  );
}

